### ISSUE TITLE
No Sources Files in the Pod Folder

### ISSUE THREAD

**Issue by wale-fingo** [growthbook/growthbook-swift#7]
After I managed to install the Pod successfully I realised that the library doesn't have any source files/folder other than the `README.md `and the `LICENSE` files. So I'm unable to initialize the SDK in my swift codes/files

**Comment by vazarkevych** [comment]
@wale-fingo thank you for an opening issue.
We have fixed the issue with the pod installation.
Please use: 
`pod 'GrowthBook-IOS'`
It should work as expected now, and all needed files should be there.

**Comment by petr-fiala** [comment]
@vazarkevych  i don't think the issue is fixed, i believe the problem is elsewhere:

i had the same problem "No Sources Files in the Pod Folder", the problem is very unfortunate folder structure of GrowthBook pod framework:
`../Pods/GrowthBook-IOS/build/GrowthBook.xcframework` for some reason the framework is nested in "build" folder.
It is usual to have these lines in gitignore:
```
build/
DerivedData/
...
```
which causes GrowthBook.xcframework is ignored by git.. and is missing in repo.
